name: Code Review

on:
  issue_comment:
    types: [created, edited]

jobs:
  code-review:
    if: github.event.comment.user.login == 'adshao' && startsWith(github.event.comment.body, 'chatgpt')
    runs-on: ubuntu-latest
    steps:
    - name: Debug 1
      run: echo ${{ github.event.comment.user.login == 'adshao' }}
    - name: Debug 2
      run: echo ${{ startsWith(github.event.comment.body, 'chatgpt') == 'true' }}
    - name: Checkout
      uses: actions/checkout@v3
    - uses: hmarr/debug-action@v2
    - name: OpenAI ChatGPT Code Review
      uses: ./
      with:
        LANGUAGE: 'English'
        PROGRAMMING_LANGUAGE: 'JavaScript'
        REVIEW_COMMENT_PREFIX: 'chatgpt:'
        FULL_REVIEW_COMMENT: 'chatgpt'
        OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
