name: Publish to Marketplace
on:
  push:
    branches:
    - main
    tags:
    - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2.4.2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install
    - name: Publish to Marketplace
      uses: MikeRalphson/github-action-publish@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
